- hosts: mysql-cluster
  vars:
    build_dir: /build
    mariadb_build_dir: "mariadb"
    scons_package_name: scons-2.5.1-1.noarch.rpm
    galera_build_dir: "galera"
    galera_build_script: "{{ build_dir }}/{{ galera_build_dir  }}/scripts/build.sh"
    downloadable_module_path: "downloadable" #Сюда качаются scons и все что устанавливается не из репозиториев
  tasks:
  - name: Installing the Developmane Tools package group...
    yum:
      name: "@Development tools"
      state: present
  
  - name: "Install Common requirements"
    action: >
      {{ ansible_pkg_mgr }}  state=present name={{ item }}
    with_items:
      - curl
      - net-tools
      - bind-utils
      - rsync
      - ntp
      - nscd
      - yum-utils
      - cmake 
      - ncurses-devel
      - boost-devel
      - check-devel
      - nano  
      - hyperv-daemons
      - hyperv-tools

     
  - name: Creating directories
    file:
      path: "{{ build_dir }}/{{ item  }}"
      state: directory
      mode: 0755
      recurse: yes
    with_items:
      - "{{ mariadb_build_dir  }}"
      - "{{ galera_build_dir  }}"
      - "{{ downloadable_module_path  }}"

  - name: Downloadings scons...
    get_url:
      url: https://sourceforge.net/projects/scons/files/scons/2.5.1/scons-2.5.1-1.noarch.rpm
      dest: "{{ build_dir  }}/{{ downloadable_module_path  }}"
      mode: 0755   

  - name: Installing scons...
    yum:
      name: "{{ build_dir  }}/{{ downloadable_module_path }}/{{ scons_package_name  }}"
      state: present

  - name: Getting builddeps for mariadb
    shell: 'yum-builddep -y  mariadb-server'
         
  - name: Cloning MariaDB server
    git:
      repo: https://github.com/MariaDB/server.git
      dest: "{{ build_dir  }}/{{ mariadb_build_dir  }}"
      clone: yes 
    
   
  - name: Cloning Galera
    git:
      repo: https://github.com/codership/galera.git     
      dest: "{{ build_dir  }}/{{galera_build_dir }}"
      clone: yes

  - name: Running CMake for MariaDB
    command: 'cmake -DWITH_WSREP=ON -DWITH_INNODB_DISALLOW_WRITES=ON'
    args:
      chdir:  "{{ build_dir }}/{{ mariadb_build_dir }}"

  - name: Building MariaDB server
    make:
      chdir: "{{ build_dir }}/{{ mariadb_build_dir  }}"   
      params:
        NUM_THREADS: ansible_processor_cores * ansible_processor_count + 1

    make:
      chdir: "{{ build_dir }}/{{ mariadb_build_dir  }}"
      target: install 

  - name: Building Galera ...
    shell: '{{ galera_build_script  }}'    

  - name: Post-install group configuration...
    
    group:
      name: mysql

  - name: Post-install usrer's configureation...
    user:
      name: mysql
      group: mysql

  - name: Postinstall rights configuration
    shell: chown -R mysql /usr/local/mysql; chgrp -R mysql /usr/local/mysql
         
  - name: Post-install conf...
    shell: cd /usr/local/mysql/; ./scripts/mysql_install_db --user=mysql

  - name: Creating SysV style startup
    shell: 'cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysql'
    args: 
      creates: /etc/init.d/mysql

  - name: chkonfig
    shell: chkconfig --add mysql
  
  - name: Enable mysql unit
    shell: systemctl enable mysql

  - name: Restarting Server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0 
    ignore_errors: true
