- name: Install Nginx
  package:
    name: nginx
    state: latest

- name: "enable nginx"
  tags:
   - nginx
  service:
    name: nginx
    state: restarted

- name: Replace Nginx config
  template:
          src=templates/nginx.conf
          dest=/etc/nginx/nginx.conf

