- hosts: '{{ target }}'
  vars:
    download_dir: "/tmp"
  tasks:
  - name: Download Epel Repo
    get_url:
      url:  http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      dest: "{{ download_dir  }}"
      mode: 0755

  - name: Download zabbix Repo
    get_url:
      url:  http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
      dest: "{{ download_dir  }}"
      mode: 0755

  - name: "install epel"
    action: >
      {{ ansible_pkg_mgr }}  state=present name={{ item }}
    with_items:
      - "{{  download_dir }}/epel-release-latest-7.noarch.rpm"
      - "{{  download_dir }}/zabbix-release-3.2-1.el7.noarch.rpm" 

  - name: "Install Common requirements"
    action: >
      {{ ansible_pkg_mgr }}  state=present name={{ item }}
    with_items:
      - curl
      - net-tools
      - bind-utils
      - rsync
      - ntp
      - nscd
      - yum-utils
      - ncurses-devel
      - nano
      - wget
      - hyperv-daemons
      - hyperv-tools
      - htop
      - zabbix-agent
 
  - name: "deploy zabbix_agentd.conf"
    copy:
      src: ./zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: root
      group: root
      mode: 0400

  - name: "restart zabbix agent"
    service:
      name: zabbix-agent
      state: restarted

