- hosts: '{{ target }}'
  vars:
    download_dir: "/tmp"
  tasks:
  - name: Download Epel Repo
    get_url:
      url:  http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      dest: "{{ download_dir  }}"
      mode: 0755

  - name: Download zabbix Repo
    tags:
      - zabbix
    get_url:
      url:  http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
      dest: "{{ download_dir  }}"
      mode: 0755

  - name: "install epel"
    action: >
      {{ ansible_pkg_mgr }}  state=present name={{ item }}
    with_items:
      - "{{  download_dir }}/epel-release-latest-7.noarch.rpm"
      - "{{  download_dir }}/zabbix-release-3.2-1.el7.noarch.rpm"
      

  - name: deploy network configuration /etc/sysconfig/network-scripts/ifcfg-eth0
    tags: 
      - net
    copy:
      src:   ./ifcfg-eth0
      dest:  /etc/sysconfig/network-scripts/ifcfg-eth0
      owner: root
      group: root
      mode:  0600

  - name: edit ifcfg-eth0
    tags:
      - net
    replace:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: 'IPADDR=XXX'
      replace: 'IPADDR={{ ansible_default_ipv4.address  }}'
      backup: yes
      backup: yes

  - name: set timezone to Europe/Moscow
    tags:
      - time
    timezone:
      name: Europe/Moscow

  - name: Restart network service for interface eth0
    tags:
      - net
    service:
      name: network
      state: restarted

  - name: "Install Common requirements"
    tags:
      - install
    action: >
      {{ ansible_pkg_mgr }}  state=latest name={{ item }}
    with_items:
      - curl
      - net-tools
      - bind-utils
      - rsync
      - ntp
      - nscd
      - yum-utils
      - ncurses-devel
      - nano
      - wget
      - hyperv-daemons
      - hyperv-tools
      - htop
      - zabbix-agent
      - adcli
      - kexec-tools 
      - mc 
      - ncompress
      - net-tools
      - ntp
      - ntpdate
      - oddjob
      - oddjob-mkhomedir
      - realmd
      - rsyslog
      - samba
      - samba-common
      - sssd
      - telnet
      - xinetd
      - python-gobject 
      - dbus
      - NetworkManager-glib
      - nm-connection-editor.x86_64
      - libsemanage-python
      - policycoreutils-python
      
  - name: deploy ntp.conf
    tags:
      - ntp
    copy:
      src: ./ntp.conf
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0600
      backup: yes

#    shell:  echo -e "server 10.124.0.141\nserver 10.124.0.142\nserver 10.7.21.15\nserver 10.193.21.12\nserver " > /etc/ntp.conf
  
  - name: deploy sssd.conf 
    tags:
      - sssd
    copy:
      src: ./sssd.conf
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600
      backup: yes
    

  - name: "deploy zabbix_agentd.conf"
    tags:
      - zabbix
    copy:
      src: ./zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: "restart zabbix agent"
    tags:
      - zabbix
    service:
      name: zabbix-agent
      state: restarted

